### ISSUE TITLE
doesn't work when $ref has an id

### ISSUE THREAD

**Issue by andreineculau** [bcherny/json-schema-to-typescript#107]
this should work

```json
{
  "id": "foo",
  "type": "object",
  "properties": {
    "foo": {
      "$ref": "foo"
    }
  },
  "additionalProperties": false
}
```

but it doesn't - json-schema-to-typescript will try to read a file called "foo", despite having a reference to a schema with id "foo"

**Comment by andreineculau** [comment]
`foo-bar` as id doesn't work either. not even `foo1`

**Comment by bcherny** [comment]
Hi @andreineculau. That is not a valid usage of `$ref`. What you want is:

```json
{
  "id": "foo",
  "type": "object",
  "properties": {
    "foo": {
      "$ref": "#"
    }
  },
  "additionalProperties": false
}
```

The issue is unrelated to the one you linked, and is simply how the JSONPointer and JSONSchema specs define $refs. If a $ref doesn't begin with `#`, it indicates a pointer to an external file (rather than a pointer to somewhere else in the current schema). See the ref.abc tests [here](https://github.com/bcherny/json-schema-to-typescript/tree/master/test/e2e), and see sections 8-9 in the JSONSchema spec [here](http://json-schema.org/latest/json-schema-core.html#rfc.section.8).

**Comment by andreineculau** [comment]
Well, fwiw that was not the case for JSON Schema v4, and that's what I have specified in my local schema's `$schema` value (missing from the example in this issue).

https://tools.ietf.org/html/draft-zyp-json-schema-04#section-7.2.3

**Comment by bcherny** [comment]
Read more carefully:

> Implementations MUST support canonical dereferencing, and MAY support inline dereferencing.

Don't rely on inline dereferencing.
