### ISSUE TITLE
Feature Request: Option to disable `[k: string]: any` without validating that additional keys are not present

### ISSUE THREAD

**Issue by dcolthorp** [bcherny/json-schema-to-typescript#153]
I'd like to propose the addition of an additional command-line argument to suppress the emission of `[k: string]: any` index signatures for object types which do not constraint the presence of additional properties.

TypeScript users always have the option of casting to `any` to access additional fields that are not specified by the type. However, objects with `[k: string]: any` are pretty unsafe to deal with, as TypeScript will not flag typos of the properties you _have_ declared.

One of our key use cases of JSON schema is to validate that APIs provide data satisfying our _minimum_ requirements and that we're programming to those minimum requirements. We don't wish to flag additional data returned by the API (which may be evolving over time) as an error condition during schema validation, but we do want TypeScript to flag our deviation from use of the validated fields as an error.

While I think the current behavior makes sense in some circumstances, I'd argue that it's a dangerous default because of the safety reduction in programming against the generated types, and that this feature should even be opt-in. I think reasonable people can disagree about that last statement, but having the ability to disable wildcard access would definitely be useful – I would set it every single time I use this package.

**Comment by bcherny** [comment]
Hi @dcolthorp! I don't think this is something we want to built in unless there is significant demand for the feature. In the meantime, I would pass your schema through `sed` or something to remove instances of `additionalProperties: true` before it makes it to json-schema-to-typescript. You might also want to consider explicitly versioning your API + schema, which is the more common way of dealing with this.

**Comment by danieletassone1981** [comment]
Hi - same problem here.

MongoDB schema:
```
      "_id": {
          "type": "objectId",
          "GUID": "fd145780-bb1b-11e8-9481-65c32425a310"
      },
```
is converted into:
```
  _id: {
    [k: string]: any;
  };
```
That make it really hard do handle.

**Comment by vanslly** [comment]
The `additionalProperties` field is mentioned in the Swagger v2 spec https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object, but lacks any clear specification other than it allows for specifying a more dynamic schema.

In the Swagger v3 spec the `additionalProperties` field has been further defined, however only until v3.0.2 is the default of `true` specified:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#properties
> additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. Consistent with JSON Schema, additionalProperties defaults to true.

I use .NET Core with Swashbuckle.AspNetCore to generate my Swagger v2 schema JSON, and other users have also caught into this issue: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/687

I have also resorted to stripping out the additional property allowance in my generated typescript models:

```JavaScript
const fs = require("fs");
const json2ts = require("json-schema-to-typescript");
const options = {
  unreachableDefinitions: true,
  style: {
    singleQuote: true
  }
};

json2ts.compileFromFile('src/app/core/api/api.swagger.json', options)
  .then(function (ts) {
    // https://github.com/bcherny/json-schema-to-typescript/issues/153
    ts = (
      ts.split('\n')
        .filter((line) => line.indexOf('[k: string]: any;') === -1)
        .join('\n')
    );

    console.log(ts);
    return fs.writeFileSync('src/app/core/api/api.models.d.ts', ts);
  });
```

**Comment by bdirito** [comment]
@bcherny I think this would be a good ticket to reopen as well.

Specifically additionalProperties defaults to *true*. https://json-schema.org/understanding-json-schema/reference/object.html 

On the other hand due to typescript not having as much expressability there are expressions that will legitimately translate to `[key: string]` (`patternProperties`)

This means no matter if you want to take care of this via a preprocessor or a postprocessor it cant be as simple as a search and replace. In the case of the preprocessor you need to *insert* `additionalProperties: false` - but only in the case of default (ie there is no existing other key of `additionalProperties`). In the case of the postprocessor you need to make sure that your `[key: string]` comes from an `additionalProperties` tag and not something like a `patternProperties` (depending on schema you might be able to filter the value being `any`)

**Comment by dcolthorp** [comment]
...me too. I continue to wish it was configurable.

Fundamentally, a type in typescript doesn't mean this is _only_ what an object has. It means it _at least means these requirements_. This is a key property of TypeScript's structural type system. The index signature just pollutes anything using types that happened to have been generated. Oh, woe is me.

(And thanks for a fantastic package we use every day! Excellent work and this is a super minor nit. 😀)

**Comment by jjwtay** [comment]
I would love if we could toggle this as well. Personally I would prefer it the most if additionalProperties were omitted in the schema itself (valid default is true according to JSON-Schema) then [key: string]: any does not get added but if it's set to true then you add it. I think the difference in behavior between JSON-Schema Validation and Typescript would be better handled this way since I can easily add additionalProperties: true if I wish to loosen my Typescript but both are the same in JSON-schema.

As an example currently we have a set of objects that all have a base set of similar attributes (think shapes) but then differ on a separate set of attributes. We currently are trying to define those with a Base type and then all the specific objects use that base type like so:

`
"allOf": [
    { "$ref": "#/$defs/baseShape" },
    { ... here goes the objects unique attributes }
]
`

We have this pattern for tons of different objects but the difference between desired behavior in JSON-Schema and Typescript is pretty stark so we end up having to settle for [key: string]: any everywhere. Obviously if we added additionalProperties: false all of our types come out as we expect for typescript but now our Schema can't validate against anything. Where as if the behavior followed only adding [key: string]: any IF we apply a additionalProperties: true then both the behavior of JSON-Schema and typescript would be as expected.

**Comment by nicojs** [comment]
I would love this toggle as well. Without it, type safety isn't really there.

I.e. this schema:

```json
{
  "title": "Todo",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    }
  }
}
```

Generates this interface:

```ts
export interface Todo {
  title?: string;
  [k: string]: any;
}
```

Which results in this being valid:

```ts
const todo: Todo = JSON.parse(myMessage);
todo.titel // => Want an error here!
```

Adding insult to injury, the `titel` property is considered to deliver an _explicit any_, so no help from `--noImplicitAny`. 

I would be happy to implement this in a PR.

How about an `--ignoreAdditionalProperties` flag?

**Comment by nicojs** [comment]
As a workaround:

```ts
const { promises: fs } = require('fs');
const { compile } = require('json-schema-to-typescript');

async function buildSchema(schemaFile) {
  const schemaJson = JSON.parse(await fs.readFile(schemaFile, 'utf8'));
  disallowAdditionalProperties(schemaJson);
  const ts = await compile(schemaJson, schemaFile);
  await fs.writeFile(`${path.parse(schemaFile).name}.d.ts`, ts);
}

function disallowAdditionalProperties(schema) {
  switch (schema.type) {
    case 'object':
      schema.additionalProperties = false;
      if (schema.properties) {
        Object.keys(schema.properties).forEach(prop => disallowAdditionalProperties(schema.properties[prop]));
      }
      break;
    case 'array':
      if (schema.items) {
        disallowAdditionalProperties(schema.items);
      }
      break;
    default:
      break;
  }

  if (schema.definitions) {
    Object.values(schema.definitions).forEach(definition => disallowAdditionalProperties(definition));
  }
}
```

**Comment by rymndhng** [comment]
Bumping this as well as a feature. The use-case we have is using `allOf` to compose our schemas. For JsonSchema validation, we have to add `additionalProperties: true` to all the schemas for them to check correctly. Ideally, the typescript definitions would not emit `[k: string]: any`

**Comment by bradleyayers** [comment]
Since I posted earlier, I'll give another update—the sed style approach did work for us, but we've ended up moving away from JSON schema entirely to io-ts, and shared interfaces between codebases via TypeScript code (specially via yarn workspaces).

**Comment by albertodiazdorado** [comment]
This feature is standard for validation libraries nowadays: https://github.com/gcanti/io-ts/blob/master/index.md#exact-types
