### ISSUE TITLE
How to generate all for OpenApi schema? Use JSONSchema4 instead?

### ISSUE THREAD

**Issue by chauey** [bcherny/json-schema-to-typescript#158]
I tried to paste in the OpenApi schema from https://github.com/Mermade/swagger2openapi/blob/master/schemas/openapi-3.0.json, but it does not generate classes for objects deeper in the graph. Is it related to "oneOf"? Advice? Thanks!

**Comment by chauey** [comment]
oh perhaps I need "unreachableDefinitions"

**Comment by bcherny** [comment]
Hi @chauey - I'm not sure what your question is. Could you clarify?

**Comment by chauey** [comment]
In the end, was mainly curious if should use JSON schema interfaces generated (the OpenApi schema has the "JSON schema" schema in there at "#/definitions/Schema") or use the JSONSChema4 classes from @types/json-schema? common question?

Also, this outputs interfaces instead of classes or interfaces AND classes right? no option to output classes (so we can add some implementation details)

Thanks!

**Comment by bcherny** [comment]
@chauey Without knowing why that particular schema was included under `definitions`, and without knowing what exactly you're using it for, it's hard to make a specific suggestion.

> Also, this outputs interfaces instead of classes or interfaces AND classes right? is there option to output classes (so we can add some implementation details)

JSTT produces interfaces, not classes, because JSON-Schema models shapes, not concrete implementations of those shapes. You can implement the generated interfaces if you want:

```ts
class MyClass implements MyGeneratedInterface {
  ...
}
```

Hope that helps!
