### ISSUE TITLE
Best practices for using outputted Typescript definitions

### ISSUE THREAD

**Issue by EvanLovely** [bcherny/json-schema-to-typescript#197]
I was curious how you tended to use the `d.ts` files. Do you just `import` them? If so, are they stripped out? Babel is leaving mine and I’m getting errors. Would love to hear your approach. Thanks for the utility!

**Comment by bcherny** [comment]
Hey there @EvanLovely! The way TypeScript works, it's types only exist at compile time for the benefit of TSC (the typechecker), you (the programmer), and other tooling. Babel should compile your TypeScript types away for you; if it's not, you might have configured it incorrectly, just Google "TypeScript Babel" for the right setup.

People use JSON-Schema for a bunch of different things. The most common use case is getting data from an API (for example, your REST API) -- if you just `fetch()` it, it'll be an untyped `any`, which is dangerous! Instead, you can type your API responses using the types generated by json-schema-to-typescript. But by itself this isn't super useful, since you could manually write types in TypeScript and not need this tool.

Where jstt is really useful is when you have types enforce in multiple places: client and server, multiple clients, or multiple servers. For examples, you can use JSON-Schema to define types for your Flask [server](https://pypi.org/project/flask-json-schema/), then use jstt to generate TypeScript typings for your frontend app. That way you have a single shared source of truth for your API types.

Hope that helps!
