### ISSUE TITLE
Change `bannerComment` property to use ESLint, since TSLint has been deprecated for quite a bit

### ISSUE THREAD

**Issue by krishnagopinath** [bcherny/json-schema-to-typescript#380]
Thank you for this wonderful project, @bcherny!

Since [TSLint was deprecated in 2019](https://blog.palantir.com/tslint-in-2019-1a144c2317a9), I wonder if it would make sense to [update the `bannerComment` property's default](https://github.com/bcherny/json-schema-to-typescript/blob/master/src/index.ts#L71) to use `eslint-disable` instead of `tslint:disable`.

**Comment by dianjuar** [comment]
This is a need.

I'm on a project that uses eslint and each time that I generate a new schema I have to modify by hand the banner.

Feels quite bad, especially having a comment just below that tolds you _DO NOT MODIFY IT BY HAND_

**Comment by DaSchTour** [comment]
For the start there could also be both

**Comment by bcherny** [comment]
PRs welcome to add ESLint suppression in addition to the existing TSLint suppression.

**Comment by dianjuar** [comment]
@bcherny I would like to implement this feature .

@bcherny I don't know how do you manage the help-wanted tag, but I would like to be assigned to this issue.

**Comment by JoshuaKGoldberg** [comment]
Can we do away with TSLint altogether, please? [TSLint's been deprecated since 2019](https://github.com/palantir/tslint/issues/4534) and hasn't received any updates for security fixes or new TypeScript syntax in years. A lot of folks get confused about the difference in terminology with _tslint_ vs. _lint_ vs. _eslint_.
