### ISSUE TITLE
Local $ref producing duplicate interfaces for definition when title is set

### ISSUE THREAD

**Issue by narkowicz** [bcherny/json-schema-to-typescript#56]
Schema using a local '$ref' to a definition in the same JSON document (have not tested against external file $ref's) is producing duplicate Interface statements causing creation of invalid .ts file. This seems to occur when the following conditions are met:
- Definition has a `title` (in these cases the title seems to have no effect on interface name in definitions)
- Definition requires a complex interface (not a standard basic type), such as an `object` with `properties` or a `string` with `enum`.

i.e. a definition such as the following, if referenced will result in a duplicate Interface in the ts output:

```
  "definitions": {
    "firstDefinition": {
      "title": "First Definition Title",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    }
  }
```

I've attached a test schema and the resulting ts output to better demonstrate the problem. Can try and assist if suitable - I understand @bcherny may be currently working on improvements to the $ref handling #44.

[localrefs.zip](https://github.com/bcherny/json-schema-to-typescript/files/546873/localrefs.zip)

**Comment by bcherny** [comment]
Thanks for the report @narkowicz. PRs are welcome - will use your fix in the new architecture.

**Comment by goodmind** [comment]
Is there any progress?

**Comment by bcherny** [comment]
> PRs are welcome

**Comment by utkuturunc** [comment]
Any ideas on how can this be done?

**Comment by bcherny** [comment]
@utkuturuncThe bug is that we think 1 interface is actually 2. My hunch is it's because the 2 interfaces are given different names in the `this.declarations` hash when we resolve them.

I would look into why we don't recognize the $ref as already resolved on [this line](https://github.com/bcherny/json-schema-to-typescript/blob/cb07ff45bdbc8083e7fa00ba24daef20ec0af0d7/src/index.ts#L169)

**Comment by utkuturunc** [comment]
I am not really familiar with the code, I am still learning. In the mean time I modified [this](https://github.com/bcherny/json-schema-to-typescript/blob/cb07ff45bdbc8083e7fa00ba24daef20ec0af0d7/src/TsTypes.ts#L186) line to not convert my names to titlecase. Instead I only made it so that it only removes `.` characters in names. Of course this is a specific workaround for a single schema but it may help some people.

I am slowly developing a theory:

Lets say we have a models named CustomerInformation and OrderInformation that should be generated as:

```
export interface CustomerInformation {
   name: string;
   ...
}

export interface OrderInformation {
   customerInformation: CustomerInformation
}
```

What this library tries to do is
```
export interface CustomerInformation {
   name: string;
   ...
}

export type customerInformation = CustomerInformation
export interface OrderInformation {
   customerInformation: customerInformation
}
```

but since by normalizing titles with upperFirst it ends up doing

```
export interface CustomerInformation {
   name: string;
   ...
}

export type CustomerInformation = CustomerInformation
export interface OrderInformation {
   customerInformation: customerInformation
}
```

Generating the middle type causes ts errors. As far as I understand from your message, I need to find why the middle type is being generated instead of using the interface that already exists.

I can look into this in the folllowing days.
