### ISSUE TITLE
typings to json?

### ISSUE THREAD

**Issue by unional** [bcherny/json-schema-to-typescript#70]
Thanks for the great work here.

I'm also looking for the opposite of this library. A library that converts typings to json schema.

Do you know of such library exist?

**Comment by bcherny** [comment]
I do not - what's the use case?

**Comment by unional** [comment]
Creating cli tool that consumes json config file. Want to generate the json schema and publish to schemaStore to support completion in VSCode.

**Comment by bcherny** [comment]
Ah, that is a good use case. The V2 version of jstt has a decent intermediate representation that could probably be reused for a reverse generator.

If you would like to contribute it to this project, I can comment back here when V2 is out. Otherwise feel free to link you project here and I can add it to the readme!

**Comment by unional** [comment]
V2? Do you mean V4? your version is currently 3.1.3.... 😛

**Comment by bcherny** [comment]
Haha not totally consistent on that front. https://github.com/bcherny/json-schema-to-typescript/tree/v2
