### ISSUE TITLE
Missing properties when using "oneOf" required validation

### ISSUE THREAD

**Issue by battmanz** [bcherny/json-schema-to-typescript#95]
Given this schema:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Demo",
  "properties": {
    "thing1": {"type": "string"},
    "thing2": {"type": "string"},
    "thing3": {"type": "string"}
  },
  "oneOf": [
    {"required": ["thing1"]},
    {"required": ["thing2"]},
    {"required": ["thing3"]}
  ]
}
```

It produces this result:

```ts
export type Demo = {
  [k: string]: any;
};
```

However, if I remove the `oneOf` validation stuff:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Demo",
  "properties": {
    "thing1": {"type": "string"},
    "thing2": {"type": "string"},
    "thing3": {"type": "string"}
  }
}
```

then I get the desired result:

```ts
export interface Demo {
  thing1?: string;
  thing2?: string;
  thing3?: string;
  [k: string]: any;
}
```

**Comment by bcherny** [comment]
@battmanz Thanks for the report, and sorry about the delayed response - I'm currently traveling.

From what I can tell (looking at [this page](https://github.com/json-schema/json-schema/wiki/anyOf,-allOf,-oneOf,-not)), your usage is not correct. You're saying "either properties#thing1, properties#thing2, or properties#thing3 should be defined". But JSON-Schema interprets your schema differently:

1. Since both `properties` and `oneOf` are defined, we look at just the one with the higher precedence (I believe this is unspecified, but JSTT treats the latter as having higher precedence; perhaps JSTT should instead throw a validation error here).
2. The 3 schemas listed in your `oneOf` clause don't inherit properties from the parent schema, unless you also add `"$extends": "demo"` and give your parent schema an ID of `"demo"` (note that `$extends` is not currently implemented by JSTT, but that's a separate issue). For example if we take your first `oneOf` (`{"required": ["thing1"]}`) the issue is that this object should also contain a key called `properties` with a definition for `thing1` (currently, this is defined on your root schema).

In short, are you sure that the desired output you gave is the correct output? If so, it would be helpful if you could link to an official JSON-Schema example or part of the spec that deals with mixing `properties` and `oneOf`/`allOf`/`anyOf`. We can also reach out to one of the JSON-Schema spec authors.

Otherwise, feel free to close this issue and correct your schema to the following:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Demo",
  "oneOf": [
    {
      "properties": {
        "thing1": {"type": "string"}
      },
      "required": ["thing1"]
    },
    {
      "properties": {
        "thing2": {"type": "string"}
      },
      "required": ["thing2"]
    },
    {
      "properties": {
        "thing3": {"type": "string"}
      },
      "required": ["thing3"]
    }
  ]
}
```

**Comment by battmanz** [comment]
If this [Stack Overflow Answer](https://stackoverflow.com/questions/24023536/json-schema-how-do-i-require-one-field-or-another-or-one-of-two-others-but-no#answer-25637397) is correct, then I would think that my schema is valid. That answer was posted in 2014, is it using an older version of the JSON-schema spec?

I will try your suggestion. That may work too. But if my original schema is valid, then it would be good for JSTT to handle that case.

**Comment by bcherny** [comment]
I don't think the schema in that answer does what the poster thinks it does, but I could be wrong!

@handrews @Relequestual @Julian Would one of the JSON-Schema experts mind chiming in?

**Comment by Julian** [comment]
@bcherny properties and oneOf aren't mutually exclusive, the interpretation of the original schema basically is "has to have exactly one of thing1, thing2, thing3, and the value of that has to be a string"

There should be test cases in the test suite that cover this, so if you're not already using it you might consider it :)

**Comment by bcherny** [comment]
I see, you're talking about [this](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/67c7b4dc84c783d204e0c3a9324a63f3f7d9444d/tests/draft6/oneOf.json#L38), right @Julian?

Do you think you can point me to where in the spec it talks about the interaction between `oneOf` and base schemas? I'm having trouble finding it.

Looking at [version 0 of the validation spec](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.5.5.2):

> An instance validates successfully against this keyword if it
   validates successfully against exactly one schema defined by this
   keyword's value.

And from [version 1](https://tools.ietf.org/html/draft-wright-json-schema-validation-01#section-6.28):

> An instance validates successfully against this keyword if it
   validates successfully against exactly one schema defined by this
   keyword's value.

**Comment by Relequestual** [comment]
@bcherny The spec doesn't specify this, however each validation key word adds a constriant. I would presume the test against base schema exists just to check that validation is applied correctly in that instance.

You're right to create a sort of order of precedence for your use case. The json schema in the example has multiple validation constraints, which can co-exist. You're trying to create a single object representation (if I understand correctly) from that validation definition.

Using `properties` and `one_of` at the same level doesn't really make sense. You would probably expect to have `definitions` which are then referenced in `one_of`.

**Comment by bcherny** [comment]
> Using properties and one_of at the same level doesn't really make sense. You would probably expect to have definitions which are then referenced in one_of.

@Relequestual 2 questions:

1. In @battmanz's original example at the top, the 3 schemas listed in the `oneOf` clause don't *implicitly* extend the base schema due to the way JSON-Schema works, do they? If **yes**, where does the spec talk about this? If **no**, absent an explicit `$extends` plus an `id` on the root schema, it's safe to remove the `oneOf` clause from the original example without loss of meaning right?
2. Does that mean that when parsing a JSON-Schema, it's not enough to detect the "type" of schema (`oneOf`, `anyOf`, `items`, etc.), but instead I need to take the intersection of all directives (eg. `items`, `anyOf`, `not`, `properties`, etc.)?

**Comment by Relequestual** [comment]
@bcherny I apologise in advance as I'm currently sleep deprived due to a recent arrival...

I'm not sure I really understand either of your questions (more the first than the second), but this is probably because of the above.

If I'm understanding the purpose of this library, you create a class type thing which can be used to validate an instance of an object (am I right?).
If so, I'll see if I can aswer your questions without understanding them based on what I think you may want to know.

I think in answer to your second question, Yes. Properties key word gives one way of validation, while oneOf / anyOf gives another. Both must be met in order for overall validation to pass.
It's possible, and totally valid, to have `oneOf` and `anyOf` for example. I'm not sure how useful such a schema might be mind.

> It should be noted that while an array element will only have to validate against one schema, object member values may have to validate against more than one schema.

https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-4.4

I THINK that may also answer your first question. Wether it's the base schema or not isn't important (as far as I understand... I could be wrong).
I'm out of office tomorrow... @handrews or @awwright may be able to help, but I know they may be away or pretty busy =/

**Comment by handrews** [comment]
The added constraint thing is briefly mentioned at https://tools.ietf.org/html/draft-wright-json-schema-validation-01#section-4.3
I'm about to head out of town so I'll have to look more deeply into this when I get back later next week.

**Comment by bcherny** [comment]
> If I'm understanding the purpose of this library, you create a class type thing which can be used to validate an instance of an object (am I right?).

@Relequestual Exactly right.

Your explanation and @handrews's link clarified my second question - thanks. I didn't realize that JSON Schema takes an *intersection* of all constraints on a schema, rather than enforcing that just one constraint is defined.

My first question is still open. To give another example, if we have this simplified schema:

```json
{
  "properties": {
    "thing1": {"type": "string"}
  },
  "oneOf": [
    {"required": ["thing1"]}
  ]
}
```

Is this schema correct? I was under the impression *it's not*, because the `thing1` referenced by the oneOf clause means:

1. Look up a property called `thing1` on the properties keyword on the given schema
2. The given schema is `{"required": ["thing1"]}`, which does not define a property called `thing1`
3. Therefore `thing1` resolves to undefined

The thing that's tripping me up is that `thing1` is defined on the *parent* schema, not on `{"required": ["thing1"]}`, which is its own schema. As I understand it, we would need to correct the schema like so:

```json
{
  "properties": {
    "thing1": {"type": "string"}
  },
  "oneOf": [{
    "extends": [{ "$ref": "#" }],
    "required": ["thing1"]
  }]
}
```

The reason this works and the previous example doesn't, is this one has `"extends": [{ "$ref": "#" }]`, so when we look up `thing1`, it now *is* defined on the current schema.

Please correct if my understanding is wrong!

**Comment by bcherny** [comment]
@battmanz Tracking the second issue in https://github.com/bcherny/json-schema-to-typescript/issues/96. I'll try to work on this, but as I'm traveling, no guarantees about getting this in soon. In the meantime, a workaround may be your best option.

**Comment by Relequestual** [comment]
I think your understanding in your example just given is correct. They are not part of the same schema in terms of validation. If you were the writer of that overall schema, you'd want to do something more like https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.5.7

(also, I'm pretty sure `extends` isn't a thing. It's something we're looking into functionality wise)

**Comment by bcherny** [comment]
Makes sense - thanks for all the help @relequestual!

@battmanz Closing this issue and tracking remaining work in #96.
